global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mlflow_model'
    static_configs:
      # Arahkan ke IP lokal Windows Anda (atau host.docker.internal jika Prometheus berjalan di dalam kontainer)
      - targets: ['host.docker.internal:8000']